// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user_study_record/v1/user_study_record.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WordId         string                 `protobuf:"bytes,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	StudyTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=study_time,json=studyTime,proto3" json:"study_time,omitempty"`
	MasteryLevel   uint32                 `protobuf:"varint,3,opt,name=mastery_level,json=masteryLevel,proto3" json:"mastery_level,omitempty"`
	ReviewCount    uint32                 `protobuf:"varint,4,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	LastReviewTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_review_time,json=lastReviewTime,proto3" json:"last_review_time,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,6,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	WordLevelId    uint32                 `protobuf:"varint,7,opt,name=word_level_id,json=wordLevelId,proto3" json:"word_level_id,omitempty"`
	Token          string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty" v:"required"` //v:required
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsertReq) Reset() {
	*x = InsertReq{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertReq) ProtoMessage() {}

func (x *InsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertReq.ProtoReflect.Descriptor instead.
func (*InsertReq) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{0}
}

func (x *InsertReq) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *InsertReq) GetStudyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StudyTime
	}
	return nil
}

func (x *InsertReq) GetMasteryLevel() uint32 {
	if x != nil {
		return x.MasteryLevel
	}
	return 0
}

func (x *InsertReq) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *InsertReq) GetLastReviewTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewTime
	}
	return nil
}

func (x *InsertReq) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *InsertReq) GetWordLevelId() uint32 {
	if x != nil {
		return x.WordLevelId
	}
	return 0
}

func (x *InsertReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type InsertRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRes) Reset() {
	*x = InsertRes{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRes) ProtoMessage() {}

func (x *InsertRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRes.ProtoReflect.Descriptor instead.
func (*InsertRes) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WordId         uint32                 `protobuf:"varint,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	StudyTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=study_time,json=studyTime,proto3" json:"study_time,omitempty"`
	MasteryLevel   uint32                 `protobuf:"varint,3,opt,name=mastery_level,json=masteryLevel,proto3" json:"mastery_level,omitempty"`
	ReviewCount    uint32                 `protobuf:"varint,4,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	LastReviewTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_review_time,json=lastReviewTime,proto3" json:"last_review_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReq) GetWordId() uint32 {
	if x != nil {
		return x.WordId
	}
	return 0
}

func (x *UpdateReq) GetStudyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StudyTime
	}
	return nil
}

func (x *UpdateReq) GetMasteryLevel() uint32 {
	if x != nil {
		return x.MasteryLevel
	}
	return 0
}

func (x *UpdateReq) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *UpdateReq) GetLastReviewTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewTime
	}
	return nil
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{3}
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{4}
}

type SearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRes) Reset() {
	*x = SearchRes{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRes) ProtoMessage() {}

func (x *SearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRes.ProtoReflect.Descriptor instead.
func (*SearchRes) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{5}
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{6}
}

type DeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRes) Reset() {
	*x = DeleteRes{}
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRes) ProtoMessage() {}

func (x *DeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_study_record_v1_user_study_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRes.ProtoReflect.Descriptor instead.
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return file_user_study_record_v1_user_study_record_proto_rawDescGZIP(), []int{7}
}

var File_user_study_record_v1_user_study_record_proto protoreflect.FileDescriptor

const file_user_study_record_v1_user_study_record_proto_rawDesc = "" +
	"\n" +
	",user_study_record/v1/user_study_record.proto\x12\x14user_study_record.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\tinsertReq\x12\x17\n" +
	"\aword_id\x18\x01 \x01(\tR\x06wordId\x129\n" +
	"\n" +
	"study_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstudyTime\x12#\n" +
	"\rmastery_level\x18\x03 \x01(\rR\fmasteryLevel\x12!\n" +
	"\freview_count\x18\x04 \x01(\rR\vreviewCount\x12D\n" +
	"\x10last_review_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReviewTime\x12\x1f\n" +
	"\vis_favorite\x18\x06 \x01(\bR\n" +
	"isFavorite\x12\"\n" +
	"\rword_level_id\x18\a \x01(\rR\vwordLevelId\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\"\x1d\n" +
	"\tinsertRes\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\xed\x01\n" +
	"\tupdateReq\x12\x17\n" +
	"\aword_id\x18\x01 \x01(\rR\x06wordId\x129\n" +
	"\n" +
	"study_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstudyTime\x12#\n" +
	"\rmastery_level\x18\x03 \x01(\rR\fmasteryLevel\x12!\n" +
	"\freview_count\x18\x04 \x01(\rR\vreviewCount\x12D\n" +
	"\x10last_review_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReviewTime\"\v\n" +
	"\tupdateRes\"\v\n" +
	"\tsearchReq\"\v\n" +
	"\tsearchRes\"\v\n" +
	"\tdeleteReq\"\v\n" +
	"\tdeleteRes2\xdd\x02\n" +
	"\x0fUserStudyRecord\x12Q\n" +
	"\rinsert_record\x12\x1f.user_study_record.v1.insertReq\x1a\x1f.user_study_record.v1.insertRes\x12Q\n" +
	"\rupdate_record\x12\x1f.user_study_record.v1.updateReq\x1a\x1f.user_study_record.v1.updateRes\x12Q\n" +
	"\rsearch_record\x12\x1f.user_study_record.v1.searchReq\x1a\x1f.user_study_record.v1.searchRes\x12Q\n" +
	"\rdelete_record\x12\x1f.user_study_record.v1.deleteReq\x1a\x1f.user_study_record.v1.deleteResB\x1fZ\x1dproxima/app/word/api/words/v1b\x06proto3"

var (
	file_user_study_record_v1_user_study_record_proto_rawDescOnce sync.Once
	file_user_study_record_v1_user_study_record_proto_rawDescData []byte
)

func file_user_study_record_v1_user_study_record_proto_rawDescGZIP() []byte {
	file_user_study_record_v1_user_study_record_proto_rawDescOnce.Do(func() {
		file_user_study_record_v1_user_study_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_study_record_v1_user_study_record_proto_rawDesc), len(file_user_study_record_v1_user_study_record_proto_rawDesc)))
	})
	return file_user_study_record_v1_user_study_record_proto_rawDescData
}

var file_user_study_record_v1_user_study_record_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_study_record_v1_user_study_record_proto_goTypes = []any{
	(*InsertReq)(nil),             // 0: user_study_record.v1.insertReq
	(*InsertRes)(nil),             // 1: user_study_record.v1.insertRes
	(*UpdateReq)(nil),             // 2: user_study_record.v1.updateReq
	(*UpdateRes)(nil),             // 3: user_study_record.v1.updateRes
	(*SearchReq)(nil),             // 4: user_study_record.v1.searchReq
	(*SearchRes)(nil),             // 5: user_study_record.v1.searchRes
	(*DeleteReq)(nil),             // 6: user_study_record.v1.deleteReq
	(*DeleteRes)(nil),             // 7: user_study_record.v1.deleteRes
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_user_study_record_v1_user_study_record_proto_depIdxs = []int32{
	8, // 0: user_study_record.v1.insertReq.study_time:type_name -> google.protobuf.Timestamp
	8, // 1: user_study_record.v1.insertReq.last_review_time:type_name -> google.protobuf.Timestamp
	8, // 2: user_study_record.v1.updateReq.study_time:type_name -> google.protobuf.Timestamp
	8, // 3: user_study_record.v1.updateReq.last_review_time:type_name -> google.protobuf.Timestamp
	0, // 4: user_study_record.v1.UserStudyRecord.insert_record:input_type -> user_study_record.v1.insertReq
	2, // 5: user_study_record.v1.UserStudyRecord.update_record:input_type -> user_study_record.v1.updateReq
	4, // 6: user_study_record.v1.UserStudyRecord.search_record:input_type -> user_study_record.v1.searchReq
	6, // 7: user_study_record.v1.UserStudyRecord.delete_record:input_type -> user_study_record.v1.deleteReq
	1, // 8: user_study_record.v1.UserStudyRecord.insert_record:output_type -> user_study_record.v1.insertRes
	3, // 9: user_study_record.v1.UserStudyRecord.update_record:output_type -> user_study_record.v1.updateRes
	5, // 10: user_study_record.v1.UserStudyRecord.search_record:output_type -> user_study_record.v1.searchRes
	7, // 11: user_study_record.v1.UserStudyRecord.delete_record:output_type -> user_study_record.v1.deleteRes
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_study_record_v1_user_study_record_proto_init() }
func file_user_study_record_v1_user_study_record_proto_init() {
	if File_user_study_record_v1_user_study_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_study_record_v1_user_study_record_proto_rawDesc), len(file_user_study_record_v1_user_study_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_study_record_v1_user_study_record_proto_goTypes,
		DependencyIndexes: file_user_study_record_v1_user_study_record_proto_depIdxs,
		MessageInfos:      file_user_study_record_v1_user_study_record_proto_msgTypes,
	}.Build()
	File_user_study_record_v1_user_study_record_proto = out.File
	file_user_study_record_v1_user_study_record_proto_goTypes = nil
	file_user_study_record_v1_user_study_record_proto_depIdxs = nil
}
