version: '3.8'

services:
  gateway:
    environment:
      - GF_SERVER_ADDRESS=:8000
      - GF_LOGGER_LEVEL=info
      - GF_GERROR_BRIEF=true
    restart: unless-stopped

  user:
    environment:
      - GF_LOGGER_LEVEL=info
      - GF_GERROR_BRIEF=true
    restart: unless-stopped

  word:
    environment:
      - GF_LOGGER_LEVEL=info
      - GF_GERROR_BRIEF=true
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  etcd:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  mongodb:
    restart: unless-stopped