// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_msg

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"proxima/app/gateway/api/user_msg"
	"proxima/app/gateway/utility"
	v1 "proxima/app/user/api/user_msg/v1"
)

type ControllerV1 struct {
	UserMsgClient v1.AccountMsgClient
}

func NewV1() user_msg.IUserMsgV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{UserMsgClient: v1.NewAccountMsgClient(conn)}
}
