// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_edit_delete

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"proxima/app/gateway/api/user_edit_delete"
	"proxima/app/gateway/utility"
	v1 "proxima/app/user/api/account_edit_delete/v1"
)

type ControllerV1 struct {
	AccountEditDelete v1.AccountEditDeleteClient
}

func NewV1() user_edit_delete.IUserEditDeleteV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{
		AccountEditDelete: v1.NewAccountEditDeleteClient(conn),
	}
}
