// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: account_edit_delete/v1/account_edit_delete.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_account_edit_delete_v1_account_edit_delete_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          int32                  `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRes) Reset() {
	*x = UpdateUserRes{}
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRes) ProtoMessage() {}

func (x *UpdateUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRes.ProtoReflect.Descriptor instead.
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return file_account_edit_delete_v1_account_edit_delete_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserRes) GetIsOK() int32 {
	if x != nil {
		return x.IsOK
	}
	return 0
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_account_edit_delete_v1_account_edit_delete_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDel         int32                  `protobuf:"varint,1,opt,name=isDel,proto3" json:"isDel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRes) Reset() {
	*x = DeleteUserRes{}
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRes) ProtoMessage() {}

func (x *DeleteUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_edit_delete_v1_account_edit_delete_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRes.ProtoReflect.Descriptor instead.
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return file_account_edit_delete_v1_account_edit_delete_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRes) GetIsDel() int32 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

var File_account_edit_delete_v1_account_edit_delete_proto protoreflect.FileDescriptor

const file_account_edit_delete_v1_account_edit_delete_proto_rawDesc = "" +
	"\n" +
	"0account_edit_delete/v1/account_edit_delete.proto\x12\x16account_edit_delete.v1\"]\n" +
	"\rUpdateUserReq\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\"#\n" +
	"\rUpdateUserRes\x12\x12\n" +
	"\x04isOK\x18\x01 \x01(\x05R\x04isOK\"\x1f\n" +
	"\rDeleteUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\rDeleteUserRes\x12\x14\n" +
	"\x05isDel\x18\x01 \x01(\x05R\x05isDel2\xd1\x01\n" +
	"\x13account_edit_delete\x12\\\n" +
	"\n" +
	"UpdateUser\x12%.account_edit_delete.v1.UpdateUserReq\x1a%.account_edit_delete.v1.UpdateUserRes\"\x00\x12\\\n" +
	"\n" +
	"DeleteUser\x12%.account_edit_delete.v1.DeleteUserReq\x1a%.account_edit_delete.v1.DeleteUserRes\"\x00B-Z+proxima/app/user/api/account_edit_delete/v1b\x06proto3"

var (
	file_account_edit_delete_v1_account_edit_delete_proto_rawDescOnce sync.Once
	file_account_edit_delete_v1_account_edit_delete_proto_rawDescData []byte
)

func file_account_edit_delete_v1_account_edit_delete_proto_rawDescGZIP() []byte {
	file_account_edit_delete_v1_account_edit_delete_proto_rawDescOnce.Do(func() {
		file_account_edit_delete_v1_account_edit_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_edit_delete_v1_account_edit_delete_proto_rawDesc), len(file_account_edit_delete_v1_account_edit_delete_proto_rawDesc)))
	})
	return file_account_edit_delete_v1_account_edit_delete_proto_rawDescData
}

var file_account_edit_delete_v1_account_edit_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_edit_delete_v1_account_edit_delete_proto_goTypes = []any{
	(*UpdateUserReq)(nil), // 0: account_edit_delete.v1.UpdateUserReq
	(*UpdateUserRes)(nil), // 1: account_edit_delete.v1.UpdateUserRes
	(*DeleteUserReq)(nil), // 2: account_edit_delete.v1.DeleteUserReq
	(*DeleteUserRes)(nil), // 3: account_edit_delete.v1.DeleteUserRes
}
var file_account_edit_delete_v1_account_edit_delete_proto_depIdxs = []int32{
	0, // 0: account_edit_delete.v1.account_edit_delete.UpdateUser:input_type -> account_edit_delete.v1.UpdateUserReq
	2, // 1: account_edit_delete.v1.account_edit_delete.DeleteUser:input_type -> account_edit_delete.v1.DeleteUserReq
	1, // 2: account_edit_delete.v1.account_edit_delete.UpdateUser:output_type -> account_edit_delete.v1.UpdateUserRes
	3, // 3: account_edit_delete.v1.account_edit_delete.DeleteUser:output_type -> account_edit_delete.v1.DeleteUserRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_edit_delete_v1_account_edit_delete_proto_init() }
func file_account_edit_delete_v1_account_edit_delete_proto_init() {
	if File_account_edit_delete_v1_account_edit_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_edit_delete_v1_account_edit_delete_proto_rawDesc), len(file_account_edit_delete_v1_account_edit_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_edit_delete_v1_account_edit_delete_proto_goTypes,
		DependencyIndexes: file_account_edit_delete_v1_account_edit_delete_proto_depIdxs,
		MessageInfos:      file_account_edit_delete_v1_account_edit_delete_proto_msgTypes,
	}.Build()
	File_account_edit_delete_v1_account_edit_delete_proto = out.File
	file_account_edit_delete_v1_account_edit_delete_proto_goTypes = nil
	file_account_edit_delete_v1_account_edit_delete_proto_depIdxs = nil
}
