// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_study_record

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"proxima/app/gateway/api/user_study_record"
	"proxima/app/gateway/utility"
	v1 "proxima/app/word/api/user_study_record/v1"
)

type ControllerV1 struct {
	UserStudyRecord v1.UserStudyRecordClient
}

func NewV1() user_study_record.IUserStudyRecordV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("word", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{
		UserStudyRecord: v1.NewUserStudyRecordClient(conn),
	}
}
