// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user_msg/v1/user_msg.proto

package v1

import (
	pbentity "proxima/app/user/api/pbentity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_user_msg_v1_user_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_v1_user_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_msg_v1_user_msg_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *pbentity.Users        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRes) Reset() {
	*x = UserInfoRes{}
	mi := &file_user_msg_v1_user_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRes) ProtoMessage() {}

func (x *UserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_v1_user_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRes.ProtoReflect.Descriptor instead.
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_msg_v1_user_msg_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRes) GetUser() *pbentity.Users {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_msg_v1_user_msg_proto protoreflect.FileDescriptor

const file_user_msg_v1_user_msg_proto_rawDesc = "" +
	"\n" +
	"\x1auser_msg/v1/user_msg.proto\x12\x0eaccount_msg.v1\x1a\x14pbentity/users.proto\"#\n" +
	"\vUserInfoReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\vUserInfoRes\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.pbentity.UsersR\x04user2U\n" +
	"\vaccount_msg\x12F\n" +
	"\bUserInfo\x12\x1b.account_msg.v1.UserInfoReq\x1a\x1b.account_msg.v1.UserInfoRes\"\x00B%Z#proxima/app/user/api/account_msg/v1b\x06proto3"

var (
	file_user_msg_v1_user_msg_proto_rawDescOnce sync.Once
	file_user_msg_v1_user_msg_proto_rawDescData []byte
)

func file_user_msg_v1_user_msg_proto_rawDescGZIP() []byte {
	file_user_msg_v1_user_msg_proto_rawDescOnce.Do(func() {
		file_user_msg_v1_user_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_msg_v1_user_msg_proto_rawDesc), len(file_user_msg_v1_user_msg_proto_rawDesc)))
	})
	return file_user_msg_v1_user_msg_proto_rawDescData
}

var file_user_msg_v1_user_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_msg_v1_user_msg_proto_goTypes = []any{
	(*UserInfoReq)(nil),    // 0: account_msg.v1.UserInfoReq
	(*UserInfoRes)(nil),    // 1: account_msg.v1.UserInfoRes
	(*pbentity.Users)(nil), // 2: pbentity.Users
}
var file_user_msg_v1_user_msg_proto_depIdxs = []int32{
	2, // 0: account_msg.v1.UserInfoRes.user:type_name -> pbentity.Users
	0, // 1: account_msg.v1.account_msg.UserInfo:input_type -> account_msg.v1.UserInfoReq
	1, // 2: account_msg.v1.account_msg.UserInfo:output_type -> account_msg.v1.UserInfoRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_msg_v1_user_msg_proto_init() }
func file_user_msg_v1_user_msg_proto_init() {
	if File_user_msg_v1_user_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_msg_v1_user_msg_proto_rawDesc), len(file_user_msg_v1_user_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_msg_v1_user_msg_proto_goTypes,
		DependencyIndexes: file_user_msg_v1_user_msg_proto_depIdxs,
		MessageInfos:      file_user_msg_v1_user_msg_proto_msgTypes,
	}.Build()
	File_user_msg_v1_user_msg_proto = out.File
	file_user_msg_v1_user_msg_proto_goTypes = nil
	file_user_msg_v1_user_msg_proto_depIdxs = nil
}
