// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_logout

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"proxima/app/gateway/api/user_logout"
	"proxima/app/gateway/utility"
	v1 "proxima/app/user/api/account_logout/v1"
)

type ControllerV1 struct {
	AccountLogout v1.AccountLogoutClient
}

func NewV1() user_logout.IUserLogoutV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{AccountLogout: v1.NewAccountLogoutClient(conn)}
}
