// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: account_logout/v1/account_logout.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogoutUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutUserReq) Reset() {
	*x = LogoutUserReq{}
	mi := &file_account_logout_v1_account_logout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutUserReq) ProtoMessage() {}

func (x *LogoutUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_logout_v1_account_logout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutUserReq.ProtoReflect.Descriptor instead.
func (*LogoutUserReq) Descriptor() ([]byte, []int) {
	return file_account_logout_v1_account_logout_proto_rawDescGZIP(), []int{0}
}

func (x *LogoutUserReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logout        bool                   `protobuf:"varint,1,opt,name=logout,proto3" json:"logout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutUserRes) Reset() {
	*x = LogoutUserRes{}
	mi := &file_account_logout_v1_account_logout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutUserRes) ProtoMessage() {}

func (x *LogoutUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_logout_v1_account_logout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutUserRes.ProtoReflect.Descriptor instead.
func (*LogoutUserRes) Descriptor() ([]byte, []int) {
	return file_account_logout_v1_account_logout_proto_rawDescGZIP(), []int{1}
}

func (x *LogoutUserRes) GetLogout() bool {
	if x != nil {
		return x.Logout
	}
	return false
}

var File_account_logout_v1_account_logout_proto protoreflect.FileDescriptor

const file_account_logout_v1_account_logout_proto_rawDesc = "" +
	"\n" +
	"&account_logout/v1/account_logout.proto\x12\x11account_logout.v1\"%\n" +
	"\rLogoutUserReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\rLogoutUserRes\x12\x16\n" +
	"\x06logout\x18\x01 \x01(\bR\x06logout2`\n" +
	"\x0eaccount_logout\x12N\n" +
	"\x06Logout\x12 .account_logout.v1.LogoutUserReq\x1a .account_logout.v1.LogoutUserRes\"\x00B(Z&proxima/app/user/api/account_logout/v1b\x06proto3"

var (
	file_account_logout_v1_account_logout_proto_rawDescOnce sync.Once
	file_account_logout_v1_account_logout_proto_rawDescData []byte
)

func file_account_logout_v1_account_logout_proto_rawDescGZIP() []byte {
	file_account_logout_v1_account_logout_proto_rawDescOnce.Do(func() {
		file_account_logout_v1_account_logout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_logout_v1_account_logout_proto_rawDesc), len(file_account_logout_v1_account_logout_proto_rawDesc)))
	})
	return file_account_logout_v1_account_logout_proto_rawDescData
}

var file_account_logout_v1_account_logout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_logout_v1_account_logout_proto_goTypes = []any{
	(*LogoutUserReq)(nil), // 0: account_logout.v1.LogoutUserReq
	(*LogoutUserRes)(nil), // 1: account_logout.v1.LogoutUserRes
}
var file_account_logout_v1_account_logout_proto_depIdxs = []int32{
	0, // 0: account_logout.v1.account_logout.Logout:input_type -> account_logout.v1.LogoutUserReq
	1, // 1: account_logout.v1.account_logout.Logout:output_type -> account_logout.v1.LogoutUserRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_logout_v1_account_logout_proto_init() }
func file_account_logout_v1_account_logout_proto_init() {
	if File_account_logout_v1_account_logout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_logout_v1_account_logout_proto_rawDesc), len(file_account_logout_v1_account_logout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_logout_v1_account_logout_proto_goTypes,
		DependencyIndexes: file_account_logout_v1_account_logout_proto_depIdxs,
		MessageInfos:      file_account_logout_v1_account_logout_proto_msgTypes,
	}.Build()
	File_account_logout_v1_account_logout_proto = out.File
	file_account_logout_v1_account_logout_proto_goTypes = nil
	file_account_logout_v1_account_logout_proto_depIdxs = nil
}
