// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: account_logout/v1/account_logout.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountLogout_Logout_FullMethodName = "/account_logout.v1.account_logout/Logout"
)

// AccountLogoutClient is the client API for AccountLogout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountLogoutClient interface {
	Logout(ctx context.Context, in *LogoutUserReq, opts ...grpc.CallOption) (*LogoutUserRes, error)
}

type accountLogoutClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountLogoutClient(cc grpc.ClientConnInterface) AccountLogoutClient {
	return &accountLogoutClient{cc}
}

func (c *accountLogoutClient) Logout(ctx context.Context, in *LogoutUserReq, opts ...grpc.CallOption) (*LogoutUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutUserRes)
	err := c.cc.Invoke(ctx, AccountLogout_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountLogoutServer is the server API for AccountLogout service.
// All implementations must embed UnimplementedAccountLogoutServer
// for forward compatibility.
type AccountLogoutServer interface {
	Logout(context.Context, *LogoutUserReq) (*LogoutUserRes, error)
	mustEmbedUnimplementedAccountLogoutServer()
}

// UnimplementedAccountLogoutServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountLogoutServer struct{}

func (UnimplementedAccountLogoutServer) Logout(context.Context, *LogoutUserReq) (*LogoutUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAccountLogoutServer) mustEmbedUnimplementedAccountLogoutServer() {}
func (UnimplementedAccountLogoutServer) testEmbeddedByValue()                       {}

// UnsafeAccountLogoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountLogoutServer will
// result in compilation errors.
type UnsafeAccountLogoutServer interface {
	mustEmbedUnimplementedAccountLogoutServer()
}

func RegisterAccountLogoutServer(s grpc.ServiceRegistrar, srv AccountLogoutServer) {
	// If the following call pancis, it indicates UnimplementedAccountLogoutServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountLogout_ServiceDesc, srv)
}

func _AccountLogout_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountLogoutServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountLogout_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountLogoutServer).Logout(ctx, req.(*LogoutUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountLogout_ServiceDesc is the grpc.ServiceDesc for AccountLogout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountLogout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account_logout.v1.account_logout",
	HandlerType: (*AccountLogoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Logout",
			Handler:    _AccountLogout_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_logout/v1/account_logout.proto",
}
